services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: frontend

  backend:
    build: ./backend
    volumes:
      - ./backend/videos:/app/videos
    ports:
      - "8000:8000"
    container_name: backend
    # Uncomment depending on how many cameras you have, you can check it in /dev folder on linux
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      # - /dev/video5:/dev/video5
      # - /dev/video6:/dev/video6
      # - /dev/video7:/dev/video7
      # - /dev/video8:/dev/video8
      # - /dev/video9:/dev/video9

    # Uncomment these lines if you have cuda available
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
